services:
  - type: web
    name: gaara-vid-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false

build:
  pythonVersion: 3.11
